

name: Helloworld

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print build message
        run: echo "build jobs"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print test message
        run: echo "test jobs"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Print deploy message
        run: echo "deploy jobs"
